#!/bin/bash

echo "Installing new packages..."
apt-get install -y xfce4 wget git unzip make gcc bc liblz4-tool libncurses5-dev libncursesw5-dev emacs
apt-get install -y linux-headers-generic linux-headers-`uname -r`
